### ISSUE TITLE
componentDidMount and componentDidUpdate similarity

### ISSUE THREAD

**Issue by bensie** [chantastic/react-cheat-sheet#37]
For some reason I have the hardest time remembering where to put "react is done, have at with DOM changes" stuff. 

`componentDidMount()` and `componentDidUpdate()` have equivalent DOM state and are the place for this. Very often you do the same stuff in these two, would be cool if the entry for these two in the cheat sheet indicated that.

Just an idea...if you're not into it no biggie.

**Comment by chantastic** [comment]
@bensie are you talking about how these often appear together to "doDomStuff"?

**Comment by bensie** [comment]
yes

**Comment by chantastic** [comment]
yah, i've been thinking about making a `patterns` project for this type of thing. definitely see it as something that comes up a lot.
