### ISSUE TITLE
`shouldComponentUpdate` description error

### ISSUE THREAD

**Issue by wonskarol** [chantastic/react-cheat-sheet#39]
I think there is a mistake in description for `shouldComponentUpdate`

>   // invoked before rendering with new props, not for initial 'render'

[Doc](https://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate) says, it's invoked with new state as well.

**Comment by chantastic** [comment]
I'm so sorry I missed this. Thank you for the help. I'm patching it now...
