### ISSUE TITLE
Calling setState in componentDidMount and componentWillReceiveProps does trigger an update

### ISSUE THREAD

**Issue by eriklharper** [chantastic/react-cheat-sheet#40]
According to the [official docs](https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops):

> If you need to update the state in response to prop changes (for example, to reset it), you may compare this.props and nextProps and perform state transitions using this.setState() in this method.

This chart says that setState does not trigger an update for `componentWillReceiveProps`, sounds like this needs to be changed to "yes", no?

![image](https://cloud.githubusercontent.com/assets/821864/19989455/df6b1f96-a1e3-11e6-841a-3e298f36c4a4.png)

**Comment by chantastic** [comment]
crazy. i wonder how i got that one wrong.

I'll update it. there are a bunch of other APIs that i need to clarify or add. i'll batch this in with those.

Thakns!

**Comment by eriklharper** [comment]
Looks like its the same deal for `componentDidMount` too (emphasis mine): 

> componentDidMount() is invoked immediately after a component is mounted. Initialization that requires DOM nodes should go here. If you need to load data from a remote endpoint, this is a good place to instantiate the network request. Setting state in this method _**will trigger**_ a re-rendering.

**Comment by chantastic** [comment]
working on patching these now...
