### ISSUE TITLE
ESNext Syntax

### ISSUE THREAD

**Issue by kmalakoff** [chantastic/react-cheat-sheet#5]
I'm looking for resources for people who want to learn React and this looks great...nice React cheat sheet! 

What would you think about adding the ESNext API? The reason I ask is that I searched for PropTypes and noticed this:

```
propTypes: {
  myProp: React.PropTypes.bool
}

// not available with React.Component
```

With ESNext and ReactComponent it should be:

```
  static propTypes = {
  myProp: React.PropTypes.bool
  }
```

I typically recommend Babel stage 0 for React projects since it makes using React even easier (IMHO).

If you agree, not sure the best way to integrate it. Could be a radio button, side-by-side comparison or a search checkbox? If not, no worries...

**Comment by chantastic** [comment]
@kmalakoff, thank you so much for taking the time write this issue!

You bring up a good point. This could definitely be improved by adding more syntaxes, particularly ES5 and ESNext.

I've thought about possibly presenting all 3 formats and allowing syntaxes to be toggled on and off but wanted to wait until I actually got a request for it. Looks like that moment has come :)

Stage 0 syntax has always felt a bit misleading to me. They're extremely volatile. I like the approach that Babel takes in enabling Stage 2+ by default. My litmus test is typically what's available at `npm install babel`.

Are there any other ESNext syntaxes that you provide meaningful benefits for a cheatsheet like this?

Thanks again for helping out. I really appreciate the ideation and discussion :)

**Comment by kmalakoff** [comment]
Great!

I used CoffeeScript for many years so moving back to JavaScript meant losing conveniences that I had taken for granted and would have assumed had been part of ES6 so I'm using Stage 0 to try to get some of them back. Specifically:

1) transform-function-bind (stage 0) - this allows me to not have to manually bind event handlers in render or the constructor:

```
export default class MyComponent extends React.Component {
  onClick = (e) => {}

  render() {
    return <a onClick={this.onClick}>Click</a>;
  }
}
```

2) transform-decorators (stage 1) - this allows me to use react-redux connect as a decorator:

```
@connect(state => ({activeThing: state.activeThing}))
export default class MyComponent extends React.Component {
  render() {
    let {activeThing} = this.props;
    return <div>{activeThing.name}</div>;
  }
}
```

3) transform-class-properties (stage 1) - this is what I originally mentioned in the above issue.


I might be using more in stage 1 (with Babel's recent plugin update, I'm having problems finding what the flags enable), but really it is not too important to me about what stage they belong to. I just want the features that make me productive like the ones above!

If you are interested in differentiating the stages for ESNext, rather than removing / ignoring them (which gives the impression that they don't exist...yet they are so useful!), maybe you can just put a `stage ${number}` beside them to let users know they are not enabled by default.

**Comment by chantastic** [comment]
I know that this has been a long-standing issue. Thank you for your patience. Now that the React documentation is written in ES6, I'll start converting the examples to ES6.
