### ISSUE TITLE
Failed to compile -- Module not found: [CaseSensitivePathsPlugin]

### ISSUE THREAD

**Issue by AnnotatedJS** [chantastic/react-cheat-sheet#50]
Context: Windows 8

After following all the instructions in the ReadMe file I got the following error message:

Failed to compile.

Error in ./src/data.js
Module not found: [CaseSensitivePathsPlugin] `D:\sandbox\react-cheat-sheet\src\data\misc.js` does not match the corresponding path on disk `Misc.js`.

 @ ./src/data.js 27:12-34

**Comment by chantastic** [comment]
thanks for reporting the issue.

the file was remaned at some some point but it looks like git choked on the update. i removed the file and added it back as the lowercase name. it should work now. please reopen the issue if it doesn't.
