### ISSUE TITLE
Missing setState

### ISSUE THREAD

**Issue by mmw** [chantastic/react-cheat-sheet#9]
No docs/entry for `setState`

**Comment by chantastic** [comment]
oh whoa! i totally missed that section of the API! the React docs are so opaque. a big part of why i made this thing.

thanks for the issue! i'll add all of the APIs on this page.

**Comment by mmw** [comment]
It's a great resource, thanks for creating it :+1:

**Comment by chantastic** [comment]
@mmw thanks again for the issue. added entries for all the component API, even though most them are deprecated, not available with `React.Component`, or not recommend. If anyone doesn't think the React team is rallying around ES6 classes, I'm gonna recommend they look at that page :)
